Repository am2558/increment-version-number, pull requests merged in 2024-03, with the labels that each got.

#27 override test 3
  text.txt
Labels: Minor Version

#28 first label
  text.txt
Labels: Bugfix Version

#30 new trigger feature label test
  text.txt
Labels: Minor Version

#32 new feature test with new_branch
  text.txt
Labels: Minor Version

#33 new feature label test fetch set to true
  text.txt
Labels: Minor Version

#34 bugfix label test
  text.txt
Labels: Bugfix Version

#36 feature demo dummy
  text.txt
Labels: Minor Version

#37 bugfix demo dummy
  text.txt
Labels: Bugfix Version

#38 new bugfix dummy
  text.txt
Labels: Bugfix Version

#39 override dummy
  text.txt
Labels: Major Version

#40 nw teest
  text.txt
Labels: Bugfix Version

#41 Feature test
  text.txt
Labels: Minor Version

#42 bugfix demo
  text.txt
Labels: Bugfix Version

#43 override demo
  text.txt
Labels: Minor Version

#47 check pr label
  text.txt
Labels: Bugfix Version

#48 pr label variable debug
  text.txt
Labels: Bugfix Version

#49 pr label debug check
  text.txt
Labels: Bugfix Version

#51 test override
  text.txt
Labels: Minor Version

#52 new override test with debug statment
  text.txt
Labels: Minor Version

#53 override test with debug statment
  text.txt
Labels: Minor Version

#54 new override test with labels as json
  text.txt
Labels: Minor Version

#55 new override test
  text.txt
Labels: Minor Version

#56 new minor override test
  text.txt
Labels: Minor Version

#57 PR_LABEL debug
  text.txt
Labels: Minor Version

#58 test json
  text.txt
Labels: Minor Version

#59 test manual override
  text.txt
Labels: Minor Version

#60 test manual override 2
  text.txt
Labels: Minor Version

#61 minor label override test
  text.txt
Labels: Minor Version

#63 Major version override test
  text.txt
Labels: Major Version

#64 multiple labels test
  text.txt
Labels: Minor Version, Bugfix Version
